#### fourth assignment(join and split)

In [1]:
import numpy as np

In [2]:
array1=np.array([1,2,3,4,5,6])
array2=np.array([7,8,9,10,11,12])
print(array1)
print(array2)

[1 2 3 4 5 6]
[ 7  8  9 10 11 12]


In [9]:
joind=np.concatenate((array1,array2),axis=0)
print(joind)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


###### vertically joining two arrays

In [5]:
vjoin=np.vstack((array1,array2))
print(vjoin)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]


###### horizontally joining two arrays

In [10]:
hjoin=np.hstack((array1,array2))
print(hjoin)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [13]:
array3=np.array([[3,44,5],[7,89,10]])
array4=np.array([[55,66,88],[22,33,11]])
print(array3)
print(array4)

[[ 3 44  5]
 [ 7 89 10]]
[[55 66 88]
 [22 33 11]]


In [15]:
newarry=np.concatenate((array3,array4),axis=1)
print(newarry)

[[ 3 44  5 55 66 88]
 [ 7 89 10 22 33 11]]


In [16]:
harry=np.hstack((array3,array4))
print(harry)

[[ 3 44  5 55 66 88]
 [ 7 89 10 22 33 11]]


In [17]:
varry=np.vstack((array3,array4))
print(varry)

[[ 3 44  5]
 [ 7 89 10]
 [55 66 88]
 [22 33 11]]


##### splitting 2d array into two

In [19]:
arry1,arry2=np.split(varry,[2],axis=0)
print(arry1)
print(arry2)

[[ 3 44  5]
 [ 7 89 10]]
[[55 66 88]
 [22 33 11]]


#### horizontally splitting two d array

In [20]:
array5=np.array([[3,4,5],[5,6,7],[8,9,10],[11,12,13]])
print(array5)

[[ 3  4  5]
 [ 5  6  7]
 [ 8  9 10]
 [11 12 13]]


In [32]:
horarray=np.hsplit(array5,[2,3])
print(horarray)

[array([[ 3,  4],
       [ 5,  6],
       [ 8,  9],
       [11, 12]]), array([[ 5],
       [ 7],
       [10],
       [13]]), array([], shape=(4, 0), dtype=int32)]


### first split occurs before the second column(index2),resulting in an array containing the first two columns of original array:[[3,4],[5,6],[8,9],[11,12]].the second split occurs before the third column,taking the remaining columns.this results in an array[[5],[7],[10],[13]].since there are no more columns after third column,final split results in an empty array with a shape of(4,0).

In [37]:
verarray=np.vsplit(array5,[1,2])
print(verarray)

[array([[3, 4, 5]]), array([[5, 6, 7]]), array([[ 8,  9, 10],
       [11, 12, 13]])]


In [39]:
verqarray=np.vsplit(array5,2)
print(verqarray)

[array([[3, 4, 5],
       [5, 6, 7]]), array([[ 8,  9, 10],
       [11, 12, 13]])]


In [50]:
array6=np.array([[[3,4,5],[2,3,4],[8,9,0],[23,34,56]]])
array7=np.array([[[6,7,8],[9,10,11],[12,13,14],[12,13,76]]])
print(array6)
print(array7)

[[[ 3  4  5]
  [ 2  3  4]
  [ 8  9  0]
  [23 34 56]]]
[[[ 6  7  8]
  [ 9 10 11]
  [12 13 14]
  [12 13 76]]]


### three dimension concatenation

In [51]:
array9=np.concatenate((array6,array7),axis=0)
print(array9)

[[[ 3  4  5]
  [ 2  3  4]
  [ 8  9  0]
  [23 34 56]]

 [[ 6  7  8]
  [ 9 10 11]
  [12 13 14]
  [12 13 76]]]


In [52]:
array10=np.hstack((array6,array7))

In [53]:
print(array10)

[[[ 3  4  5]
  [ 2  3  4]
  [ 8  9  0]
  [23 34 56]
  [ 6  7  8]
  [ 9 10 11]
  [12 13 14]
  [12 13 76]]]


In [54]:
array11=np.vstack((array6,array7))
print(array11)

[[[ 3  4  5]
  [ 2  3  4]
  [ 8  9  0]
  [23 34 56]]

 [[ 6  7  8]
  [ 9 10 11]
  [12 13 14]
  [12 13 76]]]


### splitting three dimensional array

In [55]:
sparry=np.hsplit(array9,[1,3])
print(sparry)

[array([[[3, 4, 5]],

       [[6, 7, 8]]]), array([[[ 2,  3,  4],
        [ 8,  9,  0]],

       [[ 9, 10, 11],
        [12, 13, 14]]]), array([[[23, 34, 56]],

       [[12, 13, 76]]])]


In [65]:
carray=np.vsplit(array9,2)
print(carray)

[array([[[ 3,  4,  5],
        [ 2,  3,  4],
        [ 8,  9,  0],
        [23, 34, 56]]]), array([[[ 6,  7,  8],
        [ 9, 10, 11],
        [12, 13, 14],
        [12, 13, 76]]])]
